version: '3.8'

services:

  backend:

    build: .

    container_name: smartworking-app

    ports:
    
      - "8080:8080"

  frontend:

    build: ./frontend

    container_name: smartworking-web

    ports:
      - "3000:80"